const INCREMENT_STEP = `game/INCREMENT_STEP`;
const INCREMENT_MISTAKES = `game/INCREMENT_MISTAKES`;
const SET_GAME_TIME = `game/SET_GAME_TIME`;
const DECREASE_GAME_TIME = `game/DECREASE_GAME_TIME`;
const RESET_GAME = `game/RESET_GAME`;

export default {
  INCREMENT_STEP,
  INCREMENT_MISTAKES,
  SET_GAME_TIME,
  DECREASE_GAME_TIME,
  RESET_GAME
};
